version: "3.9"

services:
  schooly-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schooly-back
    restart: unless-stopped
    networks:
      - lingua-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: school_db
      DB_USERNAME: postgres
      DB_PASSWORD: lingua123456
      STORAGE_TYPE: s3
      STORAGE_S3_ENDPOINT: http://minio:9000
      STORAGE_S3_PUBLIC_URL: https://minio.learnup.tn
      STORAGE_S3_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      STORAGE_S3_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      STORAGE_S3_BUCKET: system-files
      JWT_SECRET: 7Fr56MkCSwF0UzHRkGW6CxDqJ7zg0Sq6MmbYRwPcaVa3LO51ltcaCsvlYNipKIEFUKAl9rMOnjdGd0vdCi_syqpGs7qGIQqgxLCFE_d1z6Qvpbagv_QEsG_OMKCrMZo3_LX47HKYUlBDfxzxhZpfo_yRiY6zJ4970hlBhLz9Uh6oz-iRZ4ADkkTaJOpTgB2IStIhVad1Jx8il8J1NQDyMMC0KCoc5DoXli2ihpTLN6VR6PVJxv1OR3RnfCgCUuxCD7CY6W1mKtYTWO1lrYSsE17r2dB8_pCq3tyjjXBSO4Wugvm1I0CHC9nZVMcKpLBLkHeQQqvDPGAfyv_61W1dINVKSL63MTBytSxil7-d7HSBEhwpyX88LAGWK86roc64ae7DXP9aEBrftYrj1v4ZvufcWEnh_BovlYBWPehi6kbIjE8t21j3CrMprES1cHhULy4bs7-V7KEDgtDee-X_13bKV-Vm4-vz5iC2CtdMvWEVyiyXew-VnGWj-fVhG5p2tzZ8nmGjjuNrq-0hmR8sxqOikPUDxjZ8ZVtBadbJBurs7IxG6ws5fSBCdBHKP4AFsiyLteKLUOIUobJkK1t-3Nn6rjlZJVuIfiN6XI5X7unC0xov86cPBcLqHz_kxXXFJUzkbqw-cvDIAV4QWdOloVn48T8C4_S9BTWer65h7Is
      JWT_ACCESS_EXPIRATION_MS: ${JWT_ACCESS_EXPIRATION_MS:-900000}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXPIRATION_MS:-604800000}
      FRONTEND_URL: https://schooly.learnup.tn
      CORS_ALLOWED_ORIGINS: https://schooly.learnup.tn
      MAIL_ENABLED: ${MAIL_ENABLED:-true}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      AI_ENABLED: ${AI_ENABLED:-false}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
      TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER:-}

  schooly-front:
    build:
      context: ../school-front
      dockerfile: Dockerfile
    container_name: schooly-front
    restart: unless-stopped
    networks:
      - lingua-network

networks:
  lingua-network:
    external: true
